project:
  type: website

website:
  title: "helsel-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: Brian's Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
