project:
  type: website

website:
  navbar:
    title: Helsel Data Consulting
    logo: images/hc-logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: Brian's Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    title-block-banner: true