baseurl: /
languageCode: en-us
title: Brian Helsel's Website
theme: hugo-lithium
googleAnalytics: 'G-KW1X55P4YQ'
disqusShortname: 'https-brianhelsel-netlify-app'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Publications
      url: /publications/
      weight: 3
    - name: Projects
      url: /projects/
      weight: 4
    - name: Blog
      url: /post/
      weight: 5
    - name: Resources
      url: /resources/
      weight: 6
    - name: GitHub
      url: https://github.com/bhelsel
      weight: 8
    - name: Twitter
      url: https://twitter.com/bchelsel
      weight: 7
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: xcode
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
